### ISSUE TITLE
Add documentation in model

### ISSUE THREAD

**Issue by gsemet** [yunstanford/sanic-transmute#1]
Hello

Sanic-transmute looks very cool, I like the idea of using annotation to describe the model of the API. How can I however add human readable documentation in the model so it will be displayed in the swagger UI (which is very cool!)

**Comment by dmarkey** [comment]
+1

**Comment by yunstanford** [comment]
You can add `parameter_descriptions` in decorator `@describe`. Also function doc_string also shows up in swagger page.
