### ISSUE TITLE
openapi spec version?

### ISSUE THREAD

**Issue by swingingsimian** [yunstanford/sanic-transmute#6]
Hi

I don't see which openapi spec this supports. Does this support openapi version 3? With all the polymorphic goodness?

Thanks

Nathan

**Comment by swingingsimian** [comment]
Just realised, this is really an upstream issue, for which there is already a ticket open:
https://github.com/toumorokoshi/transmute-core/issues/43
Would that be update be automatically reflected in sanic-transmute, or would there be changes reqquired?

Thanks

**Comment by yunstanford** [comment]
It should automatically get the update
